export * from "./Settings";
export * from "./Plus";
export * from "./Logo";
export * from "./Home";
export * from "./Board";
export * from "./Profile";
export * from "./Magnifier";
export * from "./Pen";
export * from "./Trash";
